# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: alfinindrawan
          template: classic
          base: header
          config_timezone: Asia/Jakarta
          base_hireable: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_languages_limit: 6
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 18961531
          plugin_stackoverflow_sections: answers-recent, questions-recent
          plugin_stackoverflow_limit: 1
          plugin_stackoverflow_lines_snippet: 0
          plugin_stackoverflow_lines: 1
