name: pagespeed
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # Lines below let you run workflow manually and on each commit

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://alfinindrawan.com
