name: Wakatime-Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: AlfinIndrawan/metrics@master
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_TOKEN }}
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, languages-graphs, editors, os
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_user: AlfinIndrawan
