name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 00:00 API limitations
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this Readme
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE: "False"
          SHOW_OS: "False"
