name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs 4 hours
    - cron: "0 */1 * * *"

jobs:
  update-readme:
    name: Update this Readme
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_EDITORS: "False"
          SHOW_PROFILE_VIEWS: "False"
